### ISSUE TITLE
Log says backup successful but no file is made

### ISSUE THREAD

**Issue by LewisSpring** [edekeijzer/OctoPrint-WebDavBackup#12]
OctoPrint 1.5.3 Python 3.7.3 OctoPi 0.18.0

The log says that the backup was finished successfully - but the file never seems to be created.

Any ideas why? I'm sure the permissions are correct.

**Comment by edekeijzer** [comment]
Can you set _octoprint.plugins.webdavbackup_ to DEBUG logging and post the relevant entries from the logfile?

**Comment by LewisSpring** [comment]
I did so this morning - but no log appears in the list or in the log folder.

**Comment by wookie73** [comment]
Lewis

I had a similar problem.
had set WebDAV link as bellow as given in the Nextcloud documentation:
https://your.domain.com/nextcloud/remote.php/dav/files/user/
Changing this to:
https://your.domain.com/remote.php/dav/files/user/

Made everything work as it should.

Thought this might help for you?

**Comment by LewisSpring** [comment]
> Lewis
> 
> I had a similar problem.
> had set WebDAV link as bellow as given in the Nextcloud documentation:
> https://your.domain.com/nextcloud/remote.php/dav/files/user/
> Changing this to:
> https://your.domain.com/remote.php/dav/files/user/
> 
> Made everything work as it should.
> 
> Thought this might help for you?

@wookie73
I'm using Synology DSM - so i'm not sure how to get that to work for me.
I've tried

- /remote.php/dav/OctoprintBackup [OctoprintBackup is a shared folder on the root of the network share]
- /remote.php/dav/files/OctoprintBackup
- /remote.php/dav/files/User/OctoprintBackup

and I just get 200 OK back.

Thanks!

**Comment by edekeijzer** [comment]
@LewisSpring the _/remote.php/dav_ part is specific for Nextcloud. According to the Synology DSM documentation, you should just use https://your.domain.com:<port\>/ (it seems WebDAV is not listening on 443) and then put the path into the Path option.

**Comment by LewisSpring** [comment]
> @LewisSpring the _/remote.php/dav_ part is specific for Nextcloud. According to the Synology DSM documentation, you should just use https://your.domain.com:<port>/ (it seems WebDAV is not listening on 443) and then put the path into the Path option.

Ah. The DAV server is on another port - but I thought adding a port made it not work
I tried adding a port but the plugin has got into a loop of:
`2021-02-01 19:41:23,302 - octoprint.plugins.webdavbackup - DEBUG - Directory / was not found, checking parent.
2021-02-01 19:41:23,460 - py.warnings - WARNING - /home/pi/oprint/lib/python3.7/site-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.0.21'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
`

I tried with and without a / at the end and start with the same loop issue.

**Comment by LewisSpring** [comment]
If I have this here:
![image](https://user-images.githubusercontent.com/40576482/106510151-7b4edc00-64c6-11eb-92d3-54288c679eee.png)

How should I format the path box?

**Comment by LewisSpring** [comment]
The working URL is
https://192.168.0.21:5006/OctoprintBackup

**Comment by edekeijzer** [comment]
> > @LewisSpring the _/remote.php/dav_ part is specific for Nextcloud. According to the Synology DSM documentation, you should just use https://your.domain.com:/ (it seems WebDAV is not listening on 443) and then put the path into the Path option.
> 
> Ah. The DAV server is on another port - but I thought adding a port made it not work
> I tried adding a port but the plugin has got into a loop of:
> `2021-02-01 19:41:23,302 - octoprint.plugins.webdavbackup - DEBUG - Directory / was not found, checking parent. 2021-02-01 19:41:23,460 - py.warnings - WARNING - /home/pi/oprint/lib/python3.7/site-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.0.21'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings InsecureRequestWarning, `
> 
> I tried with and without a / at the end and start with the same loop issue.

This indicates that either your credentials are invalid or the WebDAV URL is incorrect, but there was a bug in the error handling that caused the loop. This has been fixed in the current release, the errors will now indicate if it's a credential or path issue.

**Comment by LewisSpring** [comment]
I'm getting new errors now.
`2021-02-07 13:00:48,788 - octoprint.plugins.webdavbackup - INFO - Backup /home/pi/.octoprint/data/backup/octoprint-backup-20210207-130048.zip created, will now attempt to upload to https://192.168.0.21:5006
2021-02-07 13:00:48,838 - py.warnings - WARNING - /home/pi/oprint/lib/python3.7/site-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.0.21'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,

2021-02-07 13:00:49,480 - octoprint.plugin - ERROR - Error while calling plugin webdavbackup
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/webdav3/client.py", line 944, in parse_free_space_response
    return int(node.text)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_webdavbackup/__init__.py", line 78, in on_event
    dav_free = davclient.free()
  File "/home/pi/oprint/lib/python3.7/site-packages/webdav3/client.py", line 66, in _wrapper
    res = fn(self, *args, **kw)
  File "/home/pi/oprint/lib/python3.7/site-packages/webdav3/client.py", line 277, in free
    return WebDavXmlUtils.parse_free_space_response(response.content, self.webdav.hostname)
  File "/home/pi/oprint/lib/python3.7/site-packages/webdav3/client.py", line 948, in parse_free_space_response
    raise MethodNotSupported(name='free', server=hostname)
webdav3.exceptions.MethodNotSupported: Method 'free' not supported for https://192.168.0.21:5006

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/__init__.py", line 271, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1890, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_webdavbackup/__init__.py", line 106, in on_event
    self._logger.error("An unexpected WebDAV error was encountered: " + exception.args)
TypeError: can only concatenate str (not "tuple") to str
`
