### ISSUE TITLE
Using WebDAVNav Server on Mac but can't get it to download

### ISSUE THREAD

**Issue by Xiondewah** [edekeijzer/OctoPrint-WebDavBackup#17]
Hi - I've installed WebDAVNav server on my Mac, set up the share but can't get the plugin to auto download any backups.

I think I've got the plugin configured correctly

![image](https://user-images.githubusercontent.com/50043329/107853402-aeba3080-6e0d-11eb-8100-16de07ccfb17.png)

Any ideas?

Thanks.

**Comment by edekeijzer** [comment]
Without any error message, there isn't much to say about this.
