### ISSUE TITLE
Synology NAS WebDAV server does not support checking of remote resources - possible solution

### ISSUE THREAD

**Issue by AndyPC54** [edekeijzer/OctoPrint-WebDavBackup#19]
The latest WebDavBackup 0.3.0 still cannot upload to a Synology NAS (DSM 6.2.3 latest, WebDAV server 2.3.4-0025).

Clearing the new 'check available space' option in the Connections Setting page gives this error when attempting to upload to the Synology:

>2021-03-09 16:23:22,078 - octoprint.plugins.webdavbackup - ERROR - Server did not return WebDAV root, something is probably wronkg with your settings.

[Note minor spelling error for 'wrong'.]

I have identified an option switch with the webdav3.client API which does allow the upload of backup files to a Synology.

> Also if your server does not support check it is possible to disable it:
>
>options = {
 >...
 >'disable_check': True
>}
>client = Client(options)
>By default checking of remote resources is enabled.

I have added this "'disable_check': True" value to the /home/pi/oprint/lib/python3.7/site-packages/octoprint_webdavbackup/\__init\__.py file in the davoptions section. Backups to the Synology now work.

This setting has the disadvantage of disabling the recursive directory searching and seemingly cannot create new sub-directories if they do not already exist.

However as a workaround it is usable if the desired remote directory already exists. Non-admin users can only upload to their home directory /homes/<username> tree.

Could you consider adding a new optional 'compatibility' switch to the Connections Setting page which passes through a 'disable_check' setting rather than the user having to hardcode it.

 This option may help users of other WebDav servers who have similar connections issues.

Regards,
Andy

**Comment by lightmaster** [comment]
Your fork with this fix seems to be working for me. Thanks.

**Comment by Ukchris79** [comment]
has this fix been deployed yet?

**Comment by edekeijzer** [comment]
@AndyPC54 thanks for your work. I have been developing some other stuff myself so I can't merge it directly, but I will backport this anytime soon.

**Comment by edekeijzer** [comment]
I've been working on this backport for the last hour and I have just looked into the webdav3 client module source. It appears that the check command is the only one using the HEAD http method so my assumption is that the Synology (and probably QNAP as well) WebDAV servers do not allow that method. The info command on the other hand uses the PROPFIND method which is used as well by free (not working) but also by list (which seems like a rather essential command for any file server to support) so that might be an alternative to use. I've pushed my modifications to the dev branch, but none of it has been tested yet.

**Comment by AndyPC54** [comment]
I have done a de-install of my PR #20 version and installed 0.4.0rc.  Then I overlaid the 2 new files from the dev branch.

With 'Disable Path Check' ticked I get following error:

> 2021-04-05 18:39:02,077 - octoprint.plugins.backup - INFO - Creating backup zip at /home/pi/.octoprint/data/backup/.octoprint-backup-20210405-183902.zip (excluded: timelapse,uploads,timelapse_tmp)...
> 2021-04-05 18:39:03,542 - octoprint.plugins.backup - INFO - ... done creating backup zip.
> 2021-04-05 18:39:03,557 - octoprint.plugins.webdavbackup - INFO - Backup /home/pi/.octoprint/data/backup/octoprint-backup-20210405-183902.zip created, will now attempt to upload to http://ds918.router.local:5005
> 2021-04-05 18:39:03,560 - octoprint.plugins.webdavbackup - WARNING - All checks for successful connection are disabled.
> 2021-04-05 18:39:03,564 - octoprint.plugins.webdavbackup - INFO - File size: 7.65 MB
> 2021-04-05 18:39:03,664 - octoprint.plugin - ERROR - Error while calling plugin webdavbackup
> Traceback (most recent call last):
>   File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_webdavbackup/__init__.py", line 212, in on_event
>     davclient.upload_sync(remote_path=upload_temp, local_path=local_file_path)
>   File "/home/pi/oprint/lib/python3.7/site-packages/webdav3/client.py", line 516, in upload_sync
>     self.upload(local_path=local_path, remote_path=remote_path)
>   File "/home/pi/oprint/lib/python3.7/site-packages/webdav3/client.py", line 452, in upload
>     self.upload_file(local_path=local_path, remote_path=remote_path)
>   File "/home/pi/oprint/lib/python3.7/site-packages/webdav3/client.py", line 66, in _wrapper
>     res = fn(self, *args, **kw)
>   File "/home/pi/oprint/lib/python3.7/site-packages/webdav3/client.py", line 503, in upload_file
>     raise RemoteParentNotFound(urn.path())
> webdav3.exceptions.RemoteParentNotFound: Remote parent for: /homes/octobackup/octoprint-backup-20210405-183902.zip.tmp not found
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/__init__.py", line 271, in call_plugin
>     result = getattr(plugin, method)(*args, **kwargs)
>   File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1890, in wrapper
>     return f(*args, **kwargs)
>   File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_webdavbackup/__init__.py", line 224, in on_event
>     self._logger.error("Something went wrong uploading the file. Since you disabled the path check, this could anything, like incorrect credentials or a non-existing directory: " + sys.exc_info()[0])
> NameError: name 'sys' is not defined

Note the  sys.exc_info()[0] doesn't seem to have worked.

I have hardcoded in 'Disable_check: True' into the davoptions section and the backup works correctly; this has been confirmed on my NAS.

> 2021-04-05 19:10:28,216 - octoprint.plugins.backup - INFO - Creating backup zip at /home/pi/.octoprint/data/backup/.octoprint-backup-20210405-191028.zip (excluded: timelapse,uploads,timelapse_tmp)...
> 2021-04-05 19:10:29,249 - octoprint.plugins.backup - INFO - ... done creating backup zip.
> 2021-04-05 19:10:29,255 - octoprint.plugins.webdavbackup - INFO - Backup /home/pi/.octoprint/data/backup/octoprint-backup-20210405-191028.zip created, will now attempt to upload to http://ds918.router.local:5005
> 2021-04-05 19:10:29,257 - octoprint.plugins.webdavbackup - WARNING - All checks for successful connection are disabled.
> 2021-04-05 19:10:29,259 - octoprint.plugins.webdavbackup - INFO - File size: 7.65 MB
> 2021-04-05 19:10:30,075 - octoprint.plugins.webdavbackup - INFO - File has been uploaded successfully to http://ds918.router.local:5005 as /homes/octobackup/octoprint-backup-20210405-191028.zip


Rather than trying to reverse engineer the webdav3.client package would it not be easier to utilise the Disable_check parameter which has been provide in the package to overcome such issues.  This works.

Your stated To-Do list are reporting errors to the user via the UI and providing a test button.  Those features would allow users to more easily self diagnose connection issues.


Regards,
Andy

**Comment by edekeijzer** [comment]
@AndyPC54 I didn't find that option in the webdav3.client documentation, but now I found it in the source. Thanks for pointing it out. You're absolutely right that reporting errors in the UI would improve usability, but I wasn't able to get that working yet. I have a day off on Wednesday so I'll probably be able to spend some time on it.

**Comment by edekeijzer** [comment]
The last commit seems to work as expected, thanks to the disable_check option.

**Comment by AndyPC54** [comment]
I have tested the 0.5.1 dev build and can confirm that it does now work with the Synology NAS when the 'Disable Path Check' box is ticked.  I haven't tested the timelapse upload feature.

I would expect uploads to now work with the QNAP NAS and other personal NAS units.

I found the reference to the Disable_check option on this page: https://pypi.org/project/webdavclient3/


Regards,
Andy

**Comment by Tigerstrength** [comment]
Works for me also! Synology Webdav. Please note that I have not encountered a restriction regarding the Webdav folder path. I used /Octoprint with a dedicated **non admin** user and have no issues with that directory. So seems like there is no need to use the home directory on a Synology.

For the help of others: 
Server = "https://x.x.x.x:5006"
Backup path (in my case) ="/Octoprint"
