### ISSUE TITLE
Local volumes/NAS servers

### ISSUE THREAD

**Issue by KenLucke** [edekeijzer/OctoPrint-WebDavBackup#2]
Is there a way you could add (or adapt) the ability to store things to a local drive (not the Pi, but the one running the web interface) or a NAS server on the local network (automatically, not by manual download)?

I rarely trust, use, or rely on "cloud" based stuff if I can avoid it - someone else is in control, has your data, and in times of need the connection to an outside source may not be available.

**Comment by edekeijzer** [comment]
@KenLucke if the NAS allows you to upload files over WebDAV, it should work. I am using Nextcloud myself, which is a self-hosted "cloud" storage, for exactly the reasons you mention. It's my own data in my own cupboard ;)
Other ways of storing data (SMB or NFS) are not within my scope.
