### ISSUE TITLE
No access to QNAP WebDAV

### ISSUE THREAD

**Issue by jb0767** [edekeijzer/OctoPrint-WebDavBackup#24]
After setup an WebDAV on my QNAP TS-453A and using WebDavBackup I wasn't able to upload any file to the server. Looking into the log file I did found the following:

_**2021-04-02 17:28:56,737 - octoprint.plugins.backup - INFO - Creating backup zip at /octoprint/octoprint/data/backup/.octoprint-backup-20210402-172856.zip (excluded: -)...
2021-04-02 17:28:56,906 - octoprint.plugins.backup - INFO - ... done creating backup zip.
2021-04-02 17:28:58,491 - octoprint.plugins.webdavbackup - INFO - Backup /octoprint/octoprint/data/backup/octoprint-backup-20210402-172856.zip created, will now attempt to upload to https://192.168.178.201:5001/3D/
2021-04-02 17:28:58,510 - py.warnings - WARNING - /usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.178.201'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(

2021-04-02 17:28:58,534 - octoprint.plugins.webdavbackup - ERROR - Server did not return WebDAV root, something is probably wrong with your settings.**_

Is there anything what needs to be done on the server? Or on the setting of OctoPi?

Best regards
Joerg

**Comment by AndyPC54** [comment]
This error also occurs when using an Synology NAS: see issue #19.

You might want to try the work around I documented:
 
"added this "'disable_check': True" value to the /home/pi/oprint/lib/python3.7/site-packages/octoprint_webdavbackup/_init_.py file in the davoptions section".

This worked for another user @lightmaster. If it works for the QNAP this will be useful information.

The plugin author @edekeijzer is planning to backport my PR #20 into the main stream soon.

Regards,
Andy

**Comment by jb0767** [comment]
[octoprint (6).log](https://github.com/edekeijzer/OctoPrint-WebDavBackup/files/6254405/octoprint.6.log)
Please see attached log file. where some more errors came up after edit the init.py as mentioned in your answer.

Best regards
Joerg

**Comment by AndyPC54** [comment]
The error "Method 'free' not supported" also occurs with the Synology.  If you clear the 'Check available space' tick box that should eliminate that error.  That should also bypass the "TypeError: int() argument" error.

The 'Unverified HTTPS request' message occurs because you are using an https://... connection; as you are connecting on your local network so could use http://... instead.

Regards,
Andy

**Comment by edekeijzer** [comment]
@jb0767 please install the release candidate 0.5.1 I have just released, this allows you to disable path checking which will most likely allow the plugin to connect to your server.

**Comment by jb0767** [comment]
I installed rc 0.5.1 with no success. I started to play around with the settings of the webserver, also with no success. See logfile
[octoprint-16.log](https://github.com/edekeijzer/OctoPrint-WebDavBackup/files/6273843/octoprint-16.log)

**Comment by Tigerstrength** [comment]
Have you tried http**S**://192.168.x.x:80/3D/ 

The log shows a HTTPS session is started, but is seems like you trying https to a http port.

Please note that Qnap default has a different port for https: https://www.qnap.com/en/how-to/tutorial/article/accessing-your-qnap-nas-remotely-with-webdav

**Comment by edekeijzer** [comment]
Are you sure you have checked the 'Disable path check' box? The error you have in your logs should only be displayed if that box is unchecked.

**Comment by jb0767** [comment]
So, finally it worked. I had to setup the QNAP NAS from the scratch. And now it works.
The following settings are on the QNAP:
![image](https://user-images.githubusercontent.com/81829354/115155345-d7fe7380-a07f-11eb-873e-e829d192d69f.png)
![image](https://user-images.githubusercontent.com/81829354/115155361-ee0c3400-a07f-11eb-8922-c483b1727515.png)
With a dedicated user & password for OctoPrint.

Here are the setting in WebDAV Backup:
![image](https://user-images.githubusercontent.com/81829354/115155443-4b07ea00-a080-11eb-9812-5b6e43894d9a.png)
 
Thank you for your support!
