### ISSUE TITLE
Error: Please make sure the libxml2 and libxslt development packages are installed.

### ISSUE THREAD

**Issue by MkLHX** [edekeijzer/OctoPrint-WebDavBackup#26]
Hi there, 

trying to install this plugin on raspberry pi 4 python -V 3.8.8 octoprint 1.6.1

i getting this error:
```
Error: Please make sure the libxml2 and libxslt development packages are installed.
```
Trying to install manually ```pip install libxml2``` and ```pip install libxslt ```

but get these errors:
```
pip install libxslt
ERROR: Could not find a version that satisfies the requirement libxslt (from versions: none)
ERROR: No matching distribution found for libxslt
```
```
pip install libxml2
ERROR: Could not find a version that satisfies the requirement libxml2 (from versions: none)
ERROR: No matching distribution found for libxml2
```

So what is the workflow to install it?

**Comment by edekeijzer** [comment]
These are not Python packages, but OS dependencies which are needed to build parts of the Python packages.
For Raspbian (on which OctoPi is based) execute: _sudo apt-get install libxml2-dev libxslt1-dev_

**Comment by MkLHX** [comment]
hum ok thanks for this information. I'm using docker image  https://github.com/OctoPrint/octoprint-docker os i think this image is missing some requirements

**Comment by edekeijzer** [comment]
> hum ok thanks for this information. I'm using docker image https://github.com/OctoPrint/octoprint-docker os i think this image is missing some requirements

That makes it a bit tricky indeed. I used the x86-64 Docker image myself for testing, which didn't require any additional packages. The problem appears to be that there are precompiled Python packages for x86-64 but not for Raspberry Pi.
You could add [PiWheels](https://www.piwheels.org/) as a package source, but I'm not sure how to make that survive a recreation of the Docker container.

**Comment by edekeijzer** [comment]
Closing this one as I'm unable to fix this, the Python libraries used require these packages and there are no alternatives that don't use these packages.

**Comment by MkLHX** [comment]
yeah of course

**Comment by viren1988** [comment]
Hi,
issue can be resolved by 
yum install libxml2 libxslt-devel
