### ISSUE TITLE
Uploaded files are missing

### ISSUE THREAD

**Issue by dwspicer** [edekeijzer/OctoPrint-WebDavBackup#27]
I am trying to get webdav backup plugin working, I have set the server name to my nextcloud server and generated a username and password within nextcloud. I have set the backup path as /OctoPrint/Backups/%Y but nothing for the filename. When I do a manual backup and watch the logs, the file is successful to my server, but when go to nextcloud and look for the files, there is nothing there. 

What am I missing? Why do I not see the files after they are uploaded

Thanks

**Comment by umsmin** [comment]
For me absolutely the same. The octoprint.log shows this

`2022-02-24 08:57:43,760 - py.warnings - WARNING - /home/pi/OctoPrint/venv/lib/python3.9/site-packages/urllib3/connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cloud.####.###'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2022-02-24 08:57:43,951 - octoprint.plugins.webdavbackup - INFO - File has been uploaded successfully to https://cloud.####.###/index.php/s/########## as /Ender-7-backup-20220224-085623.zip`


I've disabled the certificate check so the first message is about that. But he show me nothing in my Nextcloud WebDAV storage.

Thanks for help

**Comment by edekeijzer** [comment]
@dwspicer @umsmin Sorry for the delayed response. Are the directories being created in your Nextcloud instance? If not, what happens if you create the directories before the backup?
Is there any information in your *nextcloud.log*?

**Comment by TheOneValen** [comment]
I have the same issue. Plugin says it has uploaded something, but file is not there.

I do not see anything in the nextcloud logs. Can I maybe get a hint on where I can look into this further?
