### ISSUE TITLE
cant get the plugin to work

### ISSUE THREAD

**Issue by steuerzentrale** [edekeijzer/OctoPrint-WebDavBackup#28]
Hi there

first of all many thanks for this nice piece of software! I installed it via the Plugin-Manager on my Octoprint (0.18.0-1.8.2-20220809123918). I am running Web-DAV on my Synology and created an extra user for it. This user has access to a share on the NAS.
<img width="568" alt="Bildschirmfoto 2022-09-01 um 13 24 27" src="https://user-images.githubusercontent.com/75168550/187903032-8e960dac-77d4-4230-a882-c9f85274f3ee.png">

I couldnt find out in which intervals the backups are being created? I would like to check if the path is working and the backups could be stored on the share.

I also use the plugin **Backup-Scheduler**  (https://plugins.octoprint.org/plugins/backupscheduler/) but it seems that it only saves it to the Octoprint-server itself.

The goal is that the backups are written on the share and not the Octoprint-server itself.

many thanks for your help

Andrew

**Comment by edekeijzer** [comment]
@steuerzentrale please uncheck the 'Check available space' and try again. It seems that the WebDAV implementation on Synology does not support this command and will always fail.

**Comment by steuerzentrale** [comment]
many thanks for the quick reply, I will do that. when does the backup-job run in order to verify it? at the moment I dont understand truly how this plugin works, is it depended from the Backup-scheduler I installed too?

**Comment by edekeijzer** [comment]
> many thanks for the quick reply, I will do that. when does the backup-job run in order to verify it? at the moment I dont understand truly how this plugin works, is it depended from the Backup-scheduler I installed too?
This plugin does not create back-ups on itself, it just gets triggered by the 'back-up finished' hook from Octoprint, which will either on a scheduled back-up or when you create a back-up from the 'Backup & restore' tab. (for testing purposes, exclude timelapse and uploaded files, it will be a lot faster and smaller)

**Comment by steuerzentrale** [comment]
got you, now I understand how it works. actually I tried to create a backup and check if it is being written in the backup-path. I disabled the capacity check. Unfortunately it doesnt, I am pretty sure that it has to do with the way how the path is written:

I am logged in with the Web-DAV user on my Mac and have access to the desired share which is: Smarthome/octoprint:
<img width="970" alt="Bildschirmfoto 2022-09-01 um 16 46 37" src="https://user-images.githubusercontent.com/75168550/187943769-13b11278-56d8-47d4-aef6-9ca4209ce426.png">

I tried all of these pathes but none is working :S 

/volume4/Smarthome/octoprint
/Smarthome/octoprint
192.168.1.13:/volume4/Smarthome/octoprint
//192.168.1.13//Smarthome/octoprint (as per the Finder)

do you have a hint for me to determine the right way of adding the path? sorry for my "stupid" question.
