### ISSUE TITLE
Can't get Plugin to work for Synology NAS WebDAV server

### ISSUE THREAD

**Issue by feuerwasser85** [edekeijzer/OctoPrint-WebDavBackup#29]
My Environment: 
Raspberry Pi 4 with OctoPi 0.18.0 and OctoPrint 1.8.3
Synology DS920+ and DSM 7.1.1-42962 Update 1
WebDav Folder for Octoprint: /volume1/backup/OctoPrint/Backups (Volumes don't have to be in the Backup Path)

My Plugin-Settings:
Server: "https://\<SERVERNAME\>.myds.me:5006" (Let's Encrypt Certificate)
Username: "OctoPrint" (Dedicated User with permission for WebDav and Destination Folder)
Password: Only a "!", others upper and lower case
Verify certificate: Checked
Check available space: Unchecked
Backup path: "/backup/OctoPrint/Backups/"
Backup filename: "" (Empty)
Upload timelapse videos: Unchecked
Remove after upload: Unchecked

Error i'm getting:
```
2022-09-28 21:11:51,625 - octoprint.plugins.backup - INFO - Creating backup zip at /home/pi/.octoprint/data/backup/.Creality-Ender-5-Plus-backup-20220928-211151.zip (excluded: uploads,timelapse,timelapse_tmp)...
2022-09-28 21:11:59,957 - octoprint.plugins.backup - INFO - ... done creating backup zip.
2022-09-28 21:11:59,983 - octoprint.plugins.webdavbackup - INFO - Backup /home/pi/.octoprint/data/backup/Creality-Ender-5-Plus-backup-20220928-211151.zip created, will now attempt to upload to https://SERVERNAME.myds.me:5006
2022-09-28 21:11:59,989 - octoprint.plugins.webdavbackup - DEBUG - Filename for upload: Creality-Ender-5-Plus-backup-20220928-211151.zip
2022-09-28 21:11:59,990 - octoprint.plugins.webdavbackup - DEBUG - Upload location: /backup/OctoPrint/Backups/Creality-Ender-5-Plus-backup-20220928-211151.zip
2022-09-28 21:11:59,990 - octoprint.plugins.webdavbackup - DEBUG - Not checking free space, just try to check the WebDAV root.
2022-09-28 21:12:00,069 - octoprint.plugins.webdavbackup - ERROR - Server did not return WebDAV root, something is probably wrong with your settings.
```

**Comment by feuerwasser85** [comment]
Uploading via Curl works just fine:
```
pi@ender5plus:~/.octoprint/data/backup $ curl -T Creality-Ender-5-Plus-backup-20220928-211029.zip -u OctoPrint:PASSWORD https://SERVERNAME.myds.me:5006/backup/OctoPrint/Backups/
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<title>201 Created</title>
</head><body>
<h1>Created</h1>
<p>Resource /backup/OctoPrint/Backups/Creality-Ender-5-Plus-backup-20220928-211029.zip has been created.</p>
</body></html>
```

**Comment by hitnrun30** [comment]
> Uploading via Curl works just fine:
> 
> ```
> pi@ender5plus:~/.octoprint/data/backup $ curl -T Creality-Ender-5-Plus-backup-20220928-211029.zip -u OctoPrint:PASSWORD https://SERVERNAME.myds.me:5006/backup/OctoPrint/Backups/
> <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
> <html>
> <head>
> <title>201 Created</title>
> </head><body>
> <h1>Created</h1>
> <p>Resource /backup/OctoPrint/Backups/Creality-Ender-5-Plus-backup-20220928-211029.zip has been created.</p>
> </body></html>
> ```

I am having the same issue, any progress with the plugin?  I would prefer that instead of some sync curl scipt.

**Comment by edekeijzer** [comment]
Uploading through curl is not using WebDAV. I've walked through the code, the line returning the error is the first attempt of the plugin to connect to the WebDAV server using your credentials, so it's not even the path or filename or something.
Unfortunately, I do not own a Synology device to test against as they are quite popular but also seem to cause a bit more trouble than the WebDAV implementation by Nextcloud, for example.
Could you try connecting with another WebDAV client using the same credentials?

**Comment by hitnrun30** [comment]
I may be able to, but I know that the webdav server portion for the NAS is setup correctly because I set up a connection to winscp and had no issues with the credetials.

**Comment by hitnrun30** [comment]
Ok, something isn't right.  your 0.4.0 release is not the code that is in the repository.  The line we are having an error with, ironically, the word wrong is spelled "wronkg" which means that the repository either was updated before or after the release.  You need a new release, and if you could add a test button, that would be awesome to fix this issue.

**Comment by edekeijzer** [comment]
> I may be able to, but I know that the webdav server portion for the NAS is setup correctly because I set up a connection to winscp and had no issues with the credetials.

If you used WinSCP with WebDAV protocol, that's exactly what I suggested ;)

**Comment by hitnrun30** [comment]
> If you used WinSCP with WebDAV protocol, that's exactly what I suggested ;)

Here is what I used in WinSCP

![image](https://user-images.githubusercontent.com/23220612/196269850-98d553b2-a494-40fb-a768-47491d6165e7.png)

**Comment by edekeijzer** [comment]
> > If you used WinSCP with WebDAV protocol, that's exactly what I suggested ;)
> 
> Here is what I used in WinSCP
> 
> ![image](https://user-images.githubusercontent.com/23220612/196269850-98d553b2-a494-40fb-a768-47491d6165e7.png)

That's not the same hostname and username you were using in your curl example?

**Comment by hitnrun30** [comment]
> That's not the same hostname and username you were using in your curl example?

That was @feuerwasser85, I have the same issue.

**Comment by edekeijzer** [comment]
> Ok, something isn't right. your 0.4.0 release is not the code that is in the repository. The line we are having an error with, ironically, the word wrong is spelled "wronkg" which means that the repository either was updated before or after the release. You need a new release, and if you could add a test button, that would be awesome to fix this issue.

Thanks for noticing, I've had a rather busy year so I really have to dive into the code to see what I was up to 18 months ago. Probably will have to do a new release then.

**Comment by hitnrun30** [comment]
> Thanks for noticing, I've had a rather busy year so I really have to dive into the code to see what I was up to 18 months ago. Probably will have to do a new release then.

When you can, would be great.  This is the only way to get backups to a local backup.

**Comment by edekeijzer** [comment]
> > Thanks for noticing, I've had a rather busy year so I really have to dive into the code to see what I was up to 18 months ago. Probably will have to do a new release then.
> 
> When you can, would be great. This is the only way to get backups to a local backup.

I've looked into it, the 0.4.0 release was based on a different branch than the default (main) branch. This means you only receive that version when you set the release channel in Octoprint to 'dev'. Since this is quite an old release already which I forgot to push to stable, I will do so now.

**Comment by hitnrun30** [comment]
awesome, do you think it will fix our issues, also does this release have a button to test the connection?

**Comment by mikecarr** [comment]
I just tried after updating to the latest plugin and same error :-(

**Comment by ianmagnone** [comment]
Just chiming in that after installing the latest version in Octoprint it's now working with my Synology! I woke up this morning to a new backup file in the right directory on my Synology. :)

**Comment by hitnrun30** [comment]
I am still getting the error 

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1056)

**Comment by mikecarr** [comment]
@ianmagnone  can you share your settings? Mine still breaks with this, and none of the connection options checked
<img width="705" alt="image" src="https://user-images.githubusercontent.com/1970342/200660349-39a67200-6570-47f3-8551-687660c277a4.png">

**Comment by mikecarr** [comment]
Mine is working now with 0.5.1, I had to use the "Cleanup plugin data" on the Plugins page. Thank you!!

**Comment by hitnrun30** [comment]
> Mine is working now with 0.5.1, I had to use the "Cleanup plugin data" on the Plugins page. Thank you!!

I did this and I'm still getting an SSL error.  What are your settings also do you have an ssl certificate for your NAS and that is the issue.  I don't really have one.

OK i went through many hoops, created the ssl and setup everything and still no luck.  I'm still getting 
Server did not return WebDAV root, something is probably wrong with your settings.

i even installed cadaver to test and see and it had no issue connecting over once I setup the accepted the ssl

**Comment by ianmagnone** [comment]
![Screenshot 2022-11-08 at 12 13 45 PM](https://user-images.githubusercontent.com/42876012/200666102-359e96d8-5c0e-4554-a049-2cca195d8926.png)
![Screenshot 2022-11-08 at 12 13 33 PM](https://user-images.githubusercontent.com/42876012/200666108-41a56b7d-161f-48c8-8b74-2c49f6381d1d.png)

I didn't have to clear any plug-in data after the new release, it just worked on the next backup.

**Comment by hitnrun30** [comment]
> 

Mine is setup very similar, I just don't care about timelapse videos and I get below

```
2022-11-13 20:38:22,289 - octoprint.plugins.backup - INFO - Creating backup zip at /home/pi/.octoprint/data/backup/.Octopi-backup-20221113-203822.zip (excluded: uploads,timelapse,timelapse_tmp)...

2022-11-13 20:38:22,420 - octoprint.plugins.backup - INFO - ... done creating backup zip.

2022-11-13 20:38:22,456 - octoprint.plugins.webdavbackup - INFO - Backup /home/pi/.octoprint/data/backup/Octopi-backup-20221113-203822.zip created, will now attempt to upload to https://192.168.1.60:5006

2022-11-13 20:38:22,475 - octoprint.plugins.webdavbackup - WARNING - All checks for successful connection are disabled.

2022-11-13 20:38:22,482 - octoprint.plugins.webdavbackup - INFO - File size: 80.59 KB

2022-11-13 20:38:22,593 - octoprint.plugins.webdavbackup - ERROR - Something went wrong uploading the file. Since you disabled the path check, this could anything, like incorrect credentials or a non-existing directory.
```

**Comment by edekeijzer** [comment]
@hitnrun30 as the error message states, it's quite hard to tell what's going wrong. Does the path exist where you are trying to upload? What happens if you just use / as path?

**Comment by hitnrun30** [comment]
@edekeijzer The path does exist.  I also made sure that the user has access and even put cadaver on the octopi server to test and it worked.  with a path of / it just comes up with the same error.

**Comment by xIExodusIx** [comment]
Hi there,
I had the same problems to copy/move my octoprint backups to my Synology NAS, but i solved it.
1. you can't use an local IP for your server address, you must use an address like "https://myserver.xyz:5006"
2. set the hook at "Disable path check", when you leave this unset you get an "Server did not return WebDAV root" error. You can see this error in the octoprint.log.
3. I also set the hook on "Verify certificate", but I don't know if it have must set. I leave it as it is now, because it works for me.

Maybe this could help you to get your WebDAV Backup to run.

@edekeijzer: As mentioned in the other thread, Buttons for "Test Server" and "Test Path" would help a lot. Also would it be nice to get more or better to find ERROR Messages, maybe Popups and an own "WebDAV_Backup.log" could help, instead of serching through the very big octoprint.log! 

Carsten from Hamburg (Germany)

**Comment by hitnrun30** [comment]
Nope didn't work.  I even connected with my NAS with WinSCP with the same credentials and settings as in octoprint and its a no go.  I made sure to try with Disable path check both checked and unchecked.  I get this.

`2023-03-24 22:25:09,439 - octoprint.plugins.backup - INFO - Creating backup zip at /home/pi/.octoprint/data/backup/.Octopi-backup-20230324-222509.zip (excluded: uploads,timelapse,timelapse_tmp)...
2023-03-24 22:25:09,538 - octoprint.plugins.backup - INFO - ... done creating backup zip.
2023-03-24 22:25:09,573 - octoprint.plugins.webdavbackup - INFO - Backup /home/pi/.octoprint/data/backup/Octopi-backup-20230324-222509.zip created, will now attempt to upload to https://s*********.synology.me:5006/
2023-03-24 22:25:12,518 - octoprint.plugins.webdavbackup - ERROR - Server did not return WebDAV root, something is probably wrong with your settings.`

**Comment by xIExodusIx** [comment]
I'm sorry for that. 
I have these settings and it works, the only differences I can see are: "Verify Certificate" is unchecked and you don't have a tailing slash in your backup path for your NAS. Try to set a tailing slash at the end of the path. -->  /Software/OctoPrint/Backups/ and also for Timelapse!

Hope this would help.

Carsten

**Comment by xIExodusIx** [comment]
By the way! 
I run OctoPrint version 1.8.7 with OctoPi 1.0.0 on an Raspberry Pi 4 8GB, Pi OS Bullseye, and installed WebDAV Backup 0.5.1 through GIT, not via the OctoPrint Repository.

Carsten

**Comment by hitnrun30** [comment]
> 

I tried again and nope.  I have 1.8.7 octoprint and 0.18.0 octopi

**Comment by edekeijzer** [comment]
> @edekeijzer: As mentioned in the other thread, Buttons for "Test Server" and "Test Path" would help a lot. Also would it be nice to get more or better to find ERROR Messages, maybe Popups and an own "WebDAV_Backup.log" could help, instead of serching through the very big octoprint.log!
> 
> Carsten from Hamburg (Germany)

This would require some Javascript skills which I do not appear to have. I did some attempts but without any success. If anybody has the skills to create these buttons in the interface and have them trigger a function in the plugin, please send a PR. I'll manage the contents of the function then.

@hitnrun30 your log shows an error which should only be thrown with 'Disable path check' unchecked. Please enable that and try again, it seems that Synology does not always support WebDAV check (HEAD method)

**Comment by hitnrun30** [comment]
> @hitnrun30 your log shows an error which should only be thrown with 'Disable path check' unchecked. Please enable that and try again, it seems that Synology does not always support WebDAV check (HEAD method)

Did and nothing worked.

**Comment by Didel** [comment]
Just wanted to chime in as well to mention I also had a lot of trouble setting this up, except I am using a QNAP NAS instead of a Synology one. However, other than the brand and the specific settings, the problems were very similar.

Long story short, after over an hour of searching, trial and error, rebooting everything multiple times, I came to the conclusion as well that in order for the backup to be synced successfully to the NAS: 
- `check free space` option should be **_disabled_**
- `disable path check` option should be **_enabled_**
  - no variables should be used in path because of the 'disable path check' option

Only with this combination of settings, the backup can be transferred to the NAS as expected. changing any of the two options will prevent the file from being transferred successfully with one of the errors mentioned above. Having more clear errors that better indicate what is wrong would be great.

Also, instead of having to manually select the value of the 'check free space' option, it would be much better if the code could test for itself if it can determine if there is enough free space available. If there are errors preventing it from being able to perform the check, it should obviously not do the check and act as if the 'check free space' option was disabled. However, if it can determine how much free space there is, it should only proceed if enough free space is available (act as if the 'check free space' option was enabled). The same goes for the path check, although that might get tricky with the variables in the name.

**Comment by hitnrun30** [comment]
> Just wanted to chime in as well to mention I also had a lot of trouble setting this up, except I am using a QNAP NAS instead of a Synology one. However, other than the brand and the specific settings, the problems were very similar.
> 
> Long story short, after over an hour of searching, trial and error, rebooting everything multiple times, I came to the conclusion as well that in order for the backup to be synced successfully to the NAS:
> 
> * `check free space` option should be **_disabled_**
> * `disable path check` option should be **_enabled_**
>   
>   * no variables should be used in path because of the 'disable path check' option
> 
> Only with this combination of settings, the backup can be transferred to the NAS as expected. changing any of the two options will prevent the file from being transferred successfully with one of the errors mentioned above. Having more clear errors that better indicate what is wrong would be great.
> 
> Also, instead of having to manually select the value of the 'check free space' option, it would be much better if the code could test for itself if it can determine if there is enough free space available. If there are errors preventing it from being able to perform the check, it should obviously not do the check and act as if the 'check free space' option was disabled. However, if it can determine how much free space there is, it should only proceed if enough free space is available (act as if the 'check free space' option was enabled). The same goes for the path check, although that might get tricky with the variables in the name.

Thank you so much.  It finally made a backup.  I feel better knowing this is in place.

**Comment by Madcamper** [comment]
> Hi there, I had the same problems to copy/move my octoprint backups to my Synology NAS, but i solved it.
> 
> 1. you can't use an local IP for your server address, you must use an address like "https://myserver.xyz:5006"
> 2. set the hook at "Disable path check", when you leave this unset you get an "Server did not return WebDAV root" error. You can see this error in the octoprint.log.
> 3. I also set the hook on "Verify certificate", but I don't know if it have must set. I leave it as it is now, because it works for me.
> 
> Maybe this could help you to get your WebDAV Backup to run.
> 
> @edekeijzer: As mentioned in the other thread, Buttons for "Test Server" and "Test Path" would help a lot. Also would it be nice to get more or better to find ERROR Messages, maybe Popups and an own "WebDAV_Backup.log" could help, instead of serching through the very big octoprint.log!
> 
> Carsten from Hamburg (Germany)

This worked for me, specifically the "Disable path Check" part. Thanks!!
![image](https://github.com/edekeijzer/OctoPrint-WebDavBackup/assets/1126345/1deb2cd5-6246-4d7e-9002-4571aeb1f26a)

Can see the "9/29/2023" one just uploaded:

![image](https://github.com/edekeijzer/OctoPrint-WebDavBackup/assets/1126345/aabe7329-c274-4f47-8464-814d8a534b72)
