### ISSUE TITLE
Plugin does not appear after installation - setup procedure buggy?

### ISSUE THREAD

**Issue by NilsRo** [edekeijzer/OctoPrint-WebDavBackup#30]
This appears after installation of the plugin and also it is not visible in the software manager. So the installation procedure seems to be buggy. OctoPrint 1.8.3 on OctoPI 0.17

Pluginmanagementlog
Unknown installiert: 

![image](https://user-images.githubusercontent.com/51311453/194700087-57182dbd-ccc3-4d1c-b8c4-7e12ee4ebdeb.png)

Attached the log, seems to be the WebDAV client but it should not run into a missing entry in the Software Manager in my oppinion. 
[octoprint.log](https://github.com/edekeijzer/OctoPrint-WebDavBackup/files/9738853/octoprint.log)

**Comment by edekeijzer** [comment]
Probably [this](https://github.com/edekeijzer/OctoPrint-WebDavBackup#libxml2-dev-and-libxslt1-dev-raspberry-pi), you'll need to install two libraries so one of the dependencies can be compiled.
