### ISSUE TITLE
Issue installing plugin

### ISSUE THREAD

**Issue by Madcamper** [edekeijzer/OctoPrint-WebDavBackup#33]
Hi,

I am having an issue installing the plugin. It goes through what looks to be a successful install minus one section of the log and when it is done, the "Plugin Management Log" shows " 'Install Unknown'  A restart is required".

I am trying to install on Octoprint 1.9.2, running the latest version of python.

Here is the log:

Installing plugin "WebDAV Backup" from https://github.com/edekeijzer/OctoPrint-WebDavBackup/archive/main.zip...
/usr/bin/python3 -m pip --disable-pip-version-check install file:///tmp/tmprca13mue/OctoPrint-WebDavBackup-main.zip --no-cache-dir
Processing /tmp/tmprca13mue/OctoPrint-WebDavBackup-main.zip
Preparing metadata (setup.py): started
Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: OctoPrint in /usr/lib/python3.10/site-packages (from WebDAV-Backup==0.5.1) (1.9.2)
Collecting webdavclient3
Downloading webdavclient3-3.14.6.tar.gz (23 kB)
Preparing metadata (setup.py): started
Preparing metadata (setup.py): finished with status 'done'
Collecting lxml
Downloading lxml-4.9.3.tar.gz (3.6 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 722.1 kB/s eta 0:00:00
Preparing metadata (setup.py): started
error: subprocess-exited-with-error

× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [3 lines of output]
Building lxml version 4.9.3.
Building without Cython.
**Error: Please make sure the libxml2 and libxslt development packages are installed.
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.**
Preparing metadata (setup.py): finished with status 'error'
Looks like the plugin was already installed. Forcing a reinstall.
/usr/bin/python3 -m pip --disable-pip-version-check install file:///tmp/tmprca13mue/OctoPrint-WebDavBackup-main.zip --no-cache-dir --ignore-installed --force-reinstall --no-deps
Processing /tmp/tmprca13mue/OctoPrint-WebDavBackup-main.zip
Preparing metadata (setup.py): started
Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: WebDAV-Backup
Building wheel for WebDAV-Backup (setup.py): started
Building wheel for WebDAV-Backup (setup.py): finished with status 'done'
Created wheel for WebDAV-Backup: filename=WebDAV_Backup-0.5.1-py3-none-any.whl size=7258 sha256=1ced7db7f945e55c2dca74912d2d701afbef3c2bf5b63b07d9922b33c3c5e19f
Stored in directory: /tmp/pip-ephem-wheel-cache-kqa2ndn6/wheels/db/28/db/3aa697e6b2d8879e8b0d655517549d54dfd8688b632079f17e
Successfully built WebDAV-Backup
Installing collected packages: WebDAV-Backup
Successfully installed WebDAV-Backup-0.5.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Done!

**Comment by edekeijzer** [comment]
It's literally in the error:
**Error: Please make sure the libxml2 and libxslt development packages are installed.

Check [this](https://github.com/edekeijzer/OctoPrint-WebDavBackup#libxml2-dev-and-libxslt1-dev-raspberry-pi) for the solution.

**Comment by Madcamper** [comment]
There's a reason I posted :) I am running octo4a and can't install extra packages the same way as someone running rpi. Is this app therefore not compatible with octo4a instances?

**Comment by edekeijzer** [comment]
> There's a reason I posted :) I am running octo4a and can't install extra packages the same way as someone running rpi. Is this app therefore not compatible with octo4a instances?

 Apparently this octo4a is Octoprint on Android, which I didn't even know was possible. I have no idea how package management is done there, so this is indeed incompatible unless you manage to get the XML2 and XSLT dev packages there yourself.
