### ISSUE TITLE
Octoprint 1.5.3 - plugin not working as it should

### ISSUE THREAD

**Issue by LouDnl** [edekeijzer/OctoPrint-WebDavBackup#7]
Tried to install the plugin through zip file link but there were libraries missing.
After installing these libraries (libxml2-dev libxslt1-dev) the plugin installed fine.

Unfortunatly the plugin did not show up in the config menu.
Log file stated:
```
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/plugin/core.py", line 1298, in _import_plugin
    module = _load_module(module_name, spec)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/plugin/core.py", line 69, in _load_module
    return imp.load_module(name, f, filename, details)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_webdavbackup/__init__.py", line 6, in <module>
    from webdav3.client import Client
  File "/home/pi/oprint/local/lib/python2.7/site-packages/webdav3/client.py", line 10, in <module>
    from urllib.parse import unquote, urlsplit, urlparse
ImportError: No module named parse
```
Fixed with changing the following in /home/pi/oprint/local/lib/python2.7/site-packages/webdav3/client.py
`from urllib.parse import unquote, urlsplit, urlparse`
to
```
try:
    from urllib.parse import unquote, urlsplit, urlparse
except ImportError:
     from urlparse import unquote, urlsplit, urlparse
```

After Octoprint restart another error (and one after that too):
```Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/plugin/core.py", line 1298, in _import_plugin
    module = _load_module(module_name, spec)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/plugin/core.py", line 69, in _load_module
    return imp.load_module(name, f, filename, details)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_webdavbackup/__init__.py", line 6, in <module>
    from webdav3.client import Client
  File "/home/pi/oprint/local/lib/python2.7/site-packages/webdav3/client.py", line 20, in <module>
    from webdav3.connection import WebDAVSettings
  File "/home/pi/oprint/local/lib/python2.7/site-packages/webdav3/connection.py", line 4, in <module>
    from webdav3.urn import Urn
  File "/home/pi/oprint/local/lib/python2.7/site-packages/webdav3/urn.py", line 2, in <module>
    from urllib.parse import unquote, quote, urlsplit
ImportError: No module named parse
```
Fixed with changing the following in /home/pi/oprint/local/lib/python2.7/site-packages/webdav3/urn.py
`from urllib.parse import unquote, quote, urlsplit`
to
```
try:
    from urllib.parse import unquote, quote, urlsplit
except ImportError:
     from urlparse import unquote, urlparse
     from urllib import quote
```

The plugin now shows up in the config menu. It still shows an error in octoprint.log though.
```2021-01-20 20:39:08,169 - octoprint.plugins.softwareupdate - ERROR - Error while retrieving update information from plugin webdavbackup
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/__init__.py", line 198, in _get_configured_checks
    hook_checks = hook()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/util/__init__.py", line 1890, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_webdavbackup/__init__.py", line 89, in get_update_information
    displayName=self._plugin_name,
NameError: global name 'self' is not defined
```

**Comment by edekeijzer** [comment]
You seem to still be running Python 2.7? That version is not supported.

**Comment by MMetze** [comment]
I have the exact same issue on an octopi image. Everything as updated as the repository allows it and there is only pyhton2.7 provided. The Problem is not directly with this plugin, but with octopi. But the plugin does not check if the right python version is available.

Update: There is python3.5.3-1 included, but still not the default.

**Comment by LouDnl** [comment]
I'm running an Octopi image which updates itself. Python 3 is installed.

**Comment by MMetze** [comment]
If it is 0.16, or older, it will install python3 but will not use it for octoprint.
I had to make a backup, flash a new SD (0.17) and restore the backup.

**Comment by LouDnl** [comment]
> 
> 
> If it is 0.16, or older, it will install python3 but will not use it for octoprint.
> I had to make a backup, flash a new SD and restore the backup.

Yeah well my installation works just fine, as does any other plugin. Not gonna fix something that isn't broken because a plugin isn't backwards compatible ;)

**Comment by LouDnl** [comment]
> 
> 
> If it is 0.16, or older, it will install python3 but will not use it for octoprint.
> I had to make a backup, flash a new SD and restore the backup.

I run 0.17 btw

**Comment by MMetze** [comment]
And you shouldn't :)
I wrote to confirm that it works on 0.17 and later. 0.16 is not supported and that is fine.
I updated my comment above to reflect that it works on 0.17

**Comment by LouDnl** [comment]
> 
> 
> And you shouldn't :)
> I wrote to confirm that it works on 0.17 and later. 0.16 is not supported and that is fine.
> I updated my comment above to reflect that it works on 0.17

Although @edekeijzer says it's not compatible with Python 2.7, the plugin manager says it should work on Python 2.7. After changing the code from my initial post the plugin works just fine and backups are uploaded.

I just used `https://octoprint.org/blog/2020/09/10/upgrade-to-py3/` to upgrade my Octoprint to Python 3 and all is well.

**Comment by edekeijzer** [comment]
Good to hear you've been able to upgrade to python3. While 2.7 isn't "broken" in the literal meaning of the word, it _is_ unmaintained for over a year and as the blog post says, Octoprint will soon drop it's Python 2 compatibility soon.
Next to that, the library I've used for the plugin is Python 3 only, so fixing this would mean completely rewriting the plugin with another lib.
