### ISSUE TITLE
Not working on OctoPrint 1.5.3 Octopi version 0.17.0

### ISSUE THREAD

**Issue by tonyfenoll** [edekeijzer/OctoPrint-WebDavBackup#8]
Also not working on Not working on OctoPrint 1.5.3 Octopi version 0.17.0.

Installed via plugin manager and via URL.  both says instalation succesfull. And i get message to restart octopi.  But after restarting, plugin not available.

**Comment by Plarkass** [comment]
Same issue for me :
connectivity.connection_check: 8.8.8.8:53
connectivity.connection_ok: true
connectivity.enabled: true
connectivity.online: true
connectivity.resolution_check: octoprint.org
connectivity.resolution_ok: true
env.hardware.cores: 4
env.hardware.freq: 1200
env.hardware.ram: 915722240
env.os.bits: 32
env.os.id: linux
env.os.platform: linux
env.plugins.pi_support.model: Raspberry Pi 3 Model B Rev 1.2
env.plugins.pi_support.octopi_version: 0.17.0
env.plugins.pi_support.throttle_state: 0x50000
env.python.pip: 21.0
env.python.version: 3.7.3
env.python.virtualenv: true
octoprint.safe_mode: false
octoprint.version: 1.5.3

**Comment by edekeijzer** [comment]
Try to install the _libxml2-dev_ and _libxslt-dev_ packages in OctoPi. Since there's no precompiled package available for lxml, it has to be built from source and that requires these two packages.
