### ISSUE TITLE
Unsure if working or installed correctly.

### ISSUE THREAD

**Issue by wookie73** [edekeijzer/OctoPrint-WebDavBackup#9]

**Comment by wookie73** [comment]
Hi
Installed plugin OK.
Setup a specific NextCloud user for the backups.
Entered all the WebDAV information into the setup page.
Seems to all be set up ok.

How do I initiate a backup? The is no WebDAV backup section in the OctoPrint web page. The only WebDAV backup stuff I can find is in the settings.
Doing a backup the normal way just results in a normal backup not a cloud one.

What am I missing, or is it a setup issue?

Thanks Dave

**Comment by wookie73** [comment]
Just to add:
     OctoPrint 1.5.3 
     Python 3.7.3 
     OctoPi 0.17.0

**Comment by Technofrikus** [comment]
I thought it would automatically upload the Backup when done. But for me it doesnt work either. 
There is no way to get feedback what is wrong. Can it connect to the Server? Or what is the problem? That would be helpful to know.

**Comment by wookie73** [comment]
So did a bit of playing around.

I presume when the plugin is installed no extra buttons / functions are visible apart from the plugin setup options in the settings page???
Also I presume you do a backup as normal from the backup page in settings and the backup is moved to the WebDAV storage location???

If this is correct the I am guessing the plugin is installed correctly?

I have been looking through the log file and after doing a backup I this appears in the log:

2021-01-29 22:25:01,660 - octoprint.plugins.webdavbackup - INFO - Backup /home/pi/.octoprint/data/backup/octoprint-backup-20210129-222444.zip created, will now attempt to upload to https://cloud.wookie.me.uk/nextcloud/remote.php/dav/files/OctoPrint/
2021-01-29 22:25:02,545 - octoprint.plugins.webdavbackup - DEBUG - Directory OctoPrint was found.
2021-01-29 22:25:12,489 - octoprint.plugins.webdavbackup - INFO - Backup has been uploaded successfully to https://cloud.wookie.me.uk/nextcloud/remote.php/dav/files/OctoPrint/ as OctoPrint/octoprint-backup-20210129-222444.zip
2021-01-29 22:25:51,587 - octoprint.server.util.sockjs - INFO - Client connection closed: ::ffff:192.168.1.6

Yet no file appears in the nextcloud storage area.

Presuming this is something I have messed up in the settings if all of the above is correct?

**Comment by wookie73** [comment]
For anyone who has the same issue my problem was that I used:

https://your.domain.com/nextcloud/remote.php/dav/files/user/
As given in the Nextcloud documentation. Changing this to:

https://your.domain.com/remote.php/dav/files/user/

Made everything work as it should.

Also for anyone who is wondering if there should be an extra backup up button on the web interface I don't believe so.
I just do a back as per normal from the settings menu and the file is magically transported to my Nextcloud server.
